### ISSUE TITLE
issue duringthe scan

### ISSUE THREAD

**Issue by redsparksing** [ipax77/sc2dsstats#5]
Hi,
When i try to scan my replays or to show the results i get this,
do you know how to solve this issue ?
I delete and reinstalled the device.
Kind regards

![issue](https://user-images.githubusercontent.com/50663281/57773337-15ca2300-7718-11e9-8d77-bc547bf7d920.png)

**Comment by ipax77** [comment]
There was some issue with identifying the correct position of a player, sorry for that. The latest version (0.8.0.8) should handle this without crashing. 
To reinitialize your data you have to delete/rename the data file which can be found in 
File->Options->JSON_FILE
the default path is C:\Users\<username>\AppData\Local\sc2dsstats\stats.json

**Comment by redsparksing** [comment]
Thanks fo the answer, and it seems to work.
I don't know why but my last replay make the scan bug, and it seems that now when i scan, the tool scan all the replays again.

**Comment by ipax77** [comment]
Glad to hear! And yes, that is what I meant with ‚reinitialize‘. 
If you have one replay causing some issues can you send me the replay, please? ph.ilipp@web.de or discord: pax_77#2766

fixed with https://github.com/ipax77/sc2dsstats/commit/c8ea876ca81c4a19992e99ce2d898ee5686cd87a

**Comment by redsparksing** [comment]
I don't have the replay unfortunately,
i deleted them to make the scan work.
Now everything work great exept for the fact taht the replay already scanned are considered new but nothing too important.
