### ISSUE TITLE
GUI reports no new replays when replays renamed

### ISSUE THREAD

**Issue by AngleWyrm10** [ipax77/sc2dsstats#6]
I name successful replays after the champion conflicts, such as 'Raynor vs Alarak.' I still have many replays that are losses, accumulating as I play.

But when I start the app, it says no new replays found

![Untitled](https://user-images.githubusercontent.com/55937426/125184939-92f96180-e1d6-11eb-88cc-74f18e0d563d.png)

**Comment by ipax77** [comment]
Thank you for reporting!
The App is searching for "Direct Strike" to identify the replays. So if you rename them to e.g. "Direct Strike - Raynor vs Alarak" it should find the replays.

**Comment by AngleWyrm10** [comment]
Thanks, prepended "Direct Strike - " to all my replays that showed the game mode as Direct Strike in the info panel, and it started working again.
