### ISSUE TITLE
korean replay did not detected

### ISSUE THREAD

**Issue by Chaosland** [ipax77/sc2dsstats#7]
direct strike is named '다이렉트 스트라이크' at korea so scdsstats can't detected replay can you fix it? or add some configuration

/sc2dsstats.lib/Data/DSdata.cs

public static Regex rx_ds = new Regex(@"(Direct Strike.*)\.SC2Replay$|(DST.*)\.SC2Replay$", RegexOptions.Singleline);

public static Regex rx_ds = new Regex(@"(다이렉트 스트라이크.*)\.SC2Replay$|(DST.*)\.SC2Replay$", RegexOptions.Singleline);

**Comment by ipax77** [comment]
The latest version 3.0.11 now has a config "Replay Name". I didn't manage to set up SC2 in my (now Korean) test VM, so any feedback is greatly appreciated. You have to restart the app after changing this setting.

**Comment by Chaosland** [comment]
thx, it`s works perfectly
