### ISSUE TITLE
Installer CTD

### ISSUE THREAD

**Issue by AngleWyrm10** [ipax77/sc2dsstats#8]
Installer crashes about halfway through the progress bar.
v1.0.13

**Comment by ipax77** [comment]
Sometimes the electron installer bugs. To fix it you have to delete the uninstall information in the registry:

* Open the Registry ((In the search box on the taskbar, type regedit, then select Registry Editor (Desktop app) from the results.)
* Navigate to Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\
* Search for "sc2dsstats.app" (CTRL-F)
* If you find something delete the Key
* Try to install again (v3.0.13)

![image](https://user-images.githubusercontent.com/46007167/202414946-86fdc92a-e267-40ba-b198-f3f68a740a6b.png)

**This project is no longer under development, please switch to https://github.com/ipax77/dsstats. Thank you!**
